# Generated by Django 5.0.3 on 2024-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='historico_de_saude',
            new_name='historico_saude',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='telefone',
            new_name='_telefone',
        ),
        migrations.RenameField(
            model_name='solicitante',
            old_name='cpf',
            new_name='_cpf',
        ),
        migrations.AddField(
            model_name='animal',
            name='_data_entrada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, upload_to='animais/'),
        ),
    ]
