# Generated by Django 5.0.3 on 2024-03-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_rename_historico_de_saude_animal_historico_saude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'ordering': ['-data_solicitacao'], 'permissions': (('pode_aprovar', 'Pode aprovar adoções'),), 'verbose_name': 'Adoção', 'verbose_name_plural': 'Adoções'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='solicitante',
            options={'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
        migrations.AlterField(
            model_name='adocao',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='_data_entrada',
            field=models.DateTimeField(db_column='Data de Entrada', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=30, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='historico_saude',
            field=models.TextField(verbose_name='Histórico de Saúde'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=50, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='_telefone',
            field=models.CharField(db_column='Telefone', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='_cpf',
            field=models.IntegerField(db_column='CPF'),
        ),
    ]
