# Generated by Django 5.0.3 on 2024-03-23 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0003_alter_adocao_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='_data_entrada',
            field=models.DateTimeField(db_column='Data de Entrada', null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], max_length=15, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='_telefone',
            field=models.CharField(db_column='Telefone', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='_cpf',
            field=models.IntegerField(db_column='CPF', verbose_name='CPF'),
        ),
    ]
