# Generated by Django 5.0.3 on 2024-03-29 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0004_solicitante_data_cadastro_alter_animal__data_entrada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Adoção', 'verbose_name_plural': 'Adoções'},
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='_data_entrada',
            new_name='data_entrada',
        ),
        migrations.AddField(
            model_name='solicitante',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
