# Generated by Django 5.0.3 on 2024-04-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0005_alter_adocao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['id'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['id'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='solicitante',
            options={'ordering': ['id'], 'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='user',
        ),
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.TextField(choices=[('S', 'Sim'), ('N', 'Não')], default=True, max_length=1, verbose_name='Animal castrado?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='_cpf',
            field=models.CharField(db_column='CPF', max_length=14, verbose_name='CPF'),
        ),
    ]
