# Generated by Django 5.0.3 on 2024-04-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0006_alter_animal_options_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='castrado',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Animal castrado?'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=50, null=True, verbose_name='Raça'),
        ),
    ]
