# Generated by Django 4.2.11 on 2024-04-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0008_funcionario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='solicitante',
            options={'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
    ]
