# Generated by Django 4.2.11 on 2024-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0009_alter_animal_options_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='animal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='animal_nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
